version: '3.3'

services:
  postgres:
    image: postgres:13.3

    container_name: postgres

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/initDb.sql
volumes:
  db-data:

