CREATE TABLE IF NOT EXISTS accounts (
        ID BIGINT,
        BALANCE BIGINT
);
INSERT INTO accounts (ID, BALANCE)
VALUES (1, 0);

INSERT INTO accounts (ID, BALANCE)
VALUES (2, 100);

INSERT INTO accounts (ID, BALANCE)
VALUES (3, 5000);

INSERT INTO accounts (ID, BALANCE)
VALUES (4, 100000);

INSERT INTO accounts (ID, BALANCE)
VALUES (5, 1000000);